title: spideynolove.github.io
baseurl: ""
url: "https://spideynolove.github.io"
collections:
  posts:
    output: true
    permalink: /blog/:year/:title/
  projects:
    output: true
    permalink: /projects/:path/
